server:
  port: 9000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: ecommerce_service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/ecommerce/**
          filters:
            - name: CircuitBreaker
              args:
                name: ecommerceServiceCircuitBreaker
                fallbackUri: forward:/fallback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ecommerce-api-gateway
      principle-attribute: preferred_username

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: payment-service
        url: /api/v1/payment/api-docs
      - name: ecommerce-service
        url: /api/v1/ecommerce/api-docs

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s

  #Resilience4J Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

  #Resilience4J Timeout Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
